### ISSUE TITLE
Add channel Semicolon&Sons

### ISSUE THREAD

**Issue by ghost** [topicplay/YouTubeList#1]
I started a YT channel 4 months ago focusing on software founders and indie-hackers. Most videos are a behind-the-scenes tour of how I built and grew a web-app that supported me for ten years. A combo of big picture code stuff (e.g. error tracking, data integrity, CI testing) and startup-y stuff (e.g. technical SEO). Here's my first video, which is the closet thing I have right now to a channel intro: https://www.youtube.com/watch?v=aCzT-LQI6x0

I think your category "Information" is the best fit, followed by "Startup" (maybe both if you that makes sense?)

The channel on YouTube is here:

https://www.youtube.com/channel/UC17mJJnvzAa_e9qQqLIfIeQ

As for size, I'm at 2.4k subscribers between YouTube and email on-site (https://www.semicolonandsons.com/)

**Comment by w-4** [comment]
Thanks! Here's the link: https://topicplay.com/d/642-semicolonsons
Will be also updated in the README tomorrow.
