### ISSUE TITLE
Channel suggestion

### ISSUE THREAD

**Issue by avoy18** [topicplay/YouTubeList#2]
Hi there. I was wondering if I can add my channel to the list. I make websites about videogame related topics + do some coding tutorials.

Here is the link:

https://www.youtube.com/channel/UCH4p-xX4C2vzroaSIn4qIpw

Cheers!

**Comment by w-4** [comment]
Hi, sure, which topic should it be added to?

**Comment by avoy18** [comment]
Hi Wadim, can you add it to Web Dev?

**Comment by w-4** [comment]
Ok thanks! Here's the link: https://topicplay.com/d/835-solari-klipz
Will be also updated in the README tomorrow.
